export const RISK_COLUMNS = [
  { key: 'riskName',         label: '风险点名称',       flex: 2 },
  { key: 'controlMeasure',   label: '控制措施描述',     flex: 3 },
  { key: 'controlLevel',     label: '执行控制层级',     flex: 2 },
  { key: 'headDeptHQ',       label: '总部牵头部门',     flex: 2 },
  { key: 'headDeptProvince', label: '省公司牵头部门',   flex: 2 },
  { key: 'headDeptCity',     label: '地市公司牵头部门', flex: 2 },
  { key: 'headDeptCounty',   label: '县支公司牵头部门', flex: 2 },
  { key: 'controlSystem',    label: '控制制度名称',     flex: 2 },
  { key: 'controlDesc',      label: '控制制度描述',     flex: 3 },
]

export const PROCESS_GROUPS = [
  { letter: 'A', items: [{ name: '按揭贷款管理', code: 'A001' }, { name: '安全生产管理', code: 'A002' }] },
  { letter: 'B', items: [{ name: '保全服务流程管理', code: 'B001' }, { name: '保险核保管理', code: 'B002' }, { name: '保险理赔处理', code: 'B003' }, { name: '保险销售合规管理', code: 'B004' }] },
  { letter: 'C', items: [{ name: '财务报告管理', code: 'C001' }, { name: '财务预算控制', code: 'C002' }, { name: '操作风险管理', code: 'C003' }, { name: '出纳资金管理', code: 'C004' }] },
  { letter: 'D', items: [{ name: '贷款发放管理', code: 'D001' }, { name: '代理业务合规管理', code: 'D002' }] },
  { letter: 'F', items: [{ name: '法律合规管理', code: 'F001' }, { name: '反洗钱监控管理', code: 'F002' }, { name: '风险评估管理', code: 'F003' }] },
  { letter: 'G', items: [{ name: '供应商资质管理', code: 'G001' }, { name: '公文档案管理', code: 'G002' }] },
  { letter: 'H', items: [{ name: '合同审批管理', code: 'H001' }, { name: '行政后勤管理', code: 'H002' }] },
  { letter: 'J', items: [{ name: '绩效考核管理', code: 'J001' }, { name: '精算评估管理', code: 'J002' }, { name: '决策审批流程', code: 'J003' }] },
  { letter: 'K', items: [{ name: '客户服务质量管理', code: 'K001' }, { name: '客户信息安全管理', code: 'K002' }] },
  { letter: 'L', items: [{ name: '理赔支付审核', code: 'L001' }, { name: '流动性风险管理', code: 'L002' }] },
  { letter: 'M', items: [{ name: '满期保险金管理', code: 'M001' }, { name: '内部审计管理', code: 'M002' }] },
  { letter: 'N', items: [{ name: '内控自评管理', code: 'N001' }, { name: '内部培训体系', code: 'N002' }] },
  { letter: 'Q', items: [{ name: '签单业务管理', code: 'Q001' }, { name: '前台服务控制', code: 'Q002' }] },
  { letter: 'R', items: [{ name: '人力资源规划管理', code: 'R001' }, { name: '日常运营监控', code: 'R002' }] },
  { letter: 'S', items: [{ name: '审计监督管理', code: 'S001' }, { name: '数据安全防护', code: 'S002' }, { name: '索赔业务处理', code: 'S003' }] },
]

export const RISK_ITEMS = [
  {
    riskName: '精算评估方法不符合会计准则',
    controlMeasure: '精算部和财务部跟踪相关监管机构发布的会计准则等',
    controlLevel: '总公司',
    headDeptHQ: '精算部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '不适用',
  },
  {
    riskName: '合同条款存在法律风险',
    controlMeasure: '法务部门定期审查合同模板及签署流程',
    controlLevel: '省公司',
    headDeptHQ: '法务部',
    headDeptProvince: '法务合规部',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '每季度审查一次',
  },
  {
    riskName: '客户信息泄露风险',
    controlMeasure: '实施数据加密与权限分级管理制度',
    controlLevel: '总公司',
    headDeptHQ: '信息技术部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '系统自动控制',
    controlDesc: '数据脱敏及访问日志审计',
  },
  {
    riskName: '理赔审核流程不规范',
    controlMeasure: '建立理赔双人复核与自动预警机制',
    controlLevel: '地市公司',
    headDeptHQ: '理赔管理部',
    headDeptProvince: '理赔部',
    headDeptCity: '理赔岗',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '双人审核，系统自动预警超时案件',
  },
  {
    riskName: '保费收入核算错误',
    controlMeasure: '财务部门每月对保费收入进行双人复核',
    controlLevel: '总公司',
    headDeptHQ: '财务部',
    headDeptProvince: '财务核算部',
    headDeptCity: '财务岗',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '月末对账，差异超阈值自动预警',
  },
  {
    riskName: '再保险安排不充分',
    controlMeasure: '再保险部门定期评估分保比例与合规性',
    controlLevel: '总公司',
    headDeptHQ: '再保险部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '每年至少评估一次再保方案',
  },
  {
    riskName: '销售人员违规销售',
    controlMeasure: '合规部门定期抽查销售录音及回访记录',
    controlLevel: '省公司',
    headDeptHQ: '合规部',
    headDeptProvince: '合规监督部',
    headDeptCity: '合规岗',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '按月抽检，违规即触发问责流程',
  },
  {
    riskName: '系统故障导致业务中断',
    controlMeasure: '信息技术部制定并演练业务连续性预案',
    controlLevel: '总公司',
    headDeptHQ: '信息技术部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '系统自动控制',
    controlDesc: '每半年演练一次，RTO 不超过 4 小时',
  },
  {
    riskName: '准备金计提不足',
    controlMeasure: '精算部定期压力测试并向董事会报告',
    controlLevel: '总公司',
    headDeptHQ: '精算部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '每季度测试，结果提交合规委员会审阅',
  },
  {
    riskName: '关联交易定价不公允',
    controlMeasure: '审计委员会对关联交易进行独立审查',
    controlLevel: '总公司',
    headDeptHQ: '内部审计部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '每笔关联交易须经独立董事签字确认',
  },
  {
    riskName: '投诉处理不及时',
    controlMeasure: '客服中心建立投诉分级响应与闭环追踪机制',
    controlLevel: '地市公司',
    headDeptHQ: '客户服务部',
    headDeptProvince: '客户服务部',
    headDeptCity: '客服岗',
    headDeptCounty: '无',
    controlSystem: '系统自动控制',
    controlDesc: '一级投诉 24 小时内响应，超时自动升级',
  },
  {
    riskName: '印章使用管理不规范',
    controlMeasure: '行政部门实施印章专人保管与用印审批制度',
    controlLevel: '省公司',
    headDeptHQ: '行政管理部',
    headDeptProvince: '行政部',
    headDeptCity: '行政岗',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '用印须经部门负责人审批，留存台账',
  },
  {
    riskName: '外包服务商管理失控',
    controlMeasure: '采购部门对外包商进行年度资质审查与绩效评估',
    controlLevel: '总公司',
    headDeptHQ: '采购管理部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '每年评估一次，不达标触发整改或更换',
  },
  {
    riskName: '员工舞弊风险',
    controlMeasure: '建立举报渠道并定期开展廉洁合规教育',
    controlLevel: '总公司',
    headDeptHQ: '合规部',
    headDeptProvince: '合规监督部',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '匿名举报热线全年畅通，年度廉洁培训覆盖率 100%',
  },
  {
    riskName: '税务申报错误',
    controlMeasure: '财务部门每月核对税务申报数据并留存审核记录',
    controlLevel: '总公司',
    headDeptHQ: '财务部',
    headDeptProvince: '财务核算部',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '申报前须经税务专员与财务负责人双重确认',
  },
  {
    riskName: '网络安全事件应对不足',
    controlMeasure: '信息技术部制定网络安全事件应急响应预案',
    controlLevel: '总公司',
    headDeptHQ: '信息技术部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '系统自动控制',
    controlDesc: '每年至少演练一次，重大事件 2 小时内启动应急',
  },
  {
    riskName: '保单录入错误',
    controlMeasure: '核保系统设置校验规则并要求双人复核',
    controlLevel: '省公司',
    headDeptHQ: '核保部',
    headDeptProvince: '核保部',
    headDeptCity: '核保岗',
    headDeptCounty: '无',
    controlSystem: '系统自动控制',
    controlDesc: '关键字段系统自动校验，异常拦截并提示',
  },
  {
    riskName: '资金挪用风险',
    controlMeasure: '财务部门实行资金收付双签制度',
    controlLevel: '总公司',
    headDeptHQ: '财务部',
    headDeptProvince: '财务核算部',
    headDeptCity: '财务岗',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '单笔超过阈值须财务总监审批',
  },
  {
    riskName: '监管报送数据不准确',
    controlMeasure: '精算与财务部门联合核对监管报送数据',
    controlLevel: '总公司',
    headDeptHQ: '精算部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '报送前三个工作日完成数据交叉验证',
  },
  {
    riskName: '业务连续性保障不足',
    controlMeasure: '制定并定期演练业务连续性计划（BCP）',
    controlLevel: '总公司',
    headDeptHQ: '运营管理部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '每半年演练一次，演练结果提交管理层审阅',
  },
  {
    riskName: '新产品开发合规风险',
    controlMeasure: '产品开发须经法务、精算、合规三方联审',
    controlLevel: '总公司',
    headDeptHQ: '产品开发部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '上市前完成监管备案，备案材料留档',
  },
  {
    riskName: '代理人资质管理缺失',
    controlMeasure: '人力资源部定期核查代理人执照及培训记录',
    controlLevel: '省公司',
    headDeptHQ: '人力资源部',
    headDeptProvince: '人力资源部',
    headDeptCity: '人力资源岗',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '每年核查一次，过期未续证者暂停展业',
  },
  {
    riskName: '档案管理不规范',
    controlMeasure: '行政部门建立电子档案与纸质档案双轨管理制度',
    controlLevel: '省公司',
    headDeptHQ: '行政管理部',
    headDeptProvince: '行政部',
    headDeptCity: '行政岗',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '重要档案扫描归档，保存期不低于监管要求',
  },
  {
    riskName: '利率风险敞口过大',
    controlMeasure: '资产负债管理委员会定期评估利率风险并制定对冲策略',
    controlLevel: '总公司',
    headDeptHQ: '资产负债管理部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '每季度向董事会报告利率敏感性分析结果',
  },
  {
    riskName: '反欺诈识别能力不足',
    controlMeasure: '理赔部门引入智能反欺诈模型辅助核查',
    controlLevel: '总公司',
    headDeptHQ: '理赔管理部',
    headDeptProvince: '理赔部',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '系统自动控制',
    controlDesc: '高风险案件自动标记，转人工复核',
  },
  {
    riskName: '费用超支风险',
    controlMeasure: '财务部门实施费用预算管控与月度偏差分析',
    controlLevel: '总公司',
    headDeptHQ: '财务部',
    headDeptProvince: '财务核算部',
    headDeptCity: '财务岗',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '超预算 10% 以上须申请追加审批',
  },
  {
    riskName: '信息披露不合规',
    controlMeasure: '合规部门审核对外信息披露内容并留存记录',
    controlLevel: '总公司',
    headDeptHQ: '合规部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '日常步骤操作',
    controlDesc: '披露前须法务与合规双重审核签字',
  },
  {
    riskName: '客户适当性评估缺失',
    controlMeasure: '销售人员在投保前完成客户风险承受能力评估',
    controlLevel: '省公司',
    headDeptHQ: '销售管理部',
    headDeptProvince: '销售部',
    headDeptCity: '销售岗',
    headDeptCounty: '无',
    controlSystem: '系统自动控制',
    controlDesc: '系统强制完成评估问卷方可进入投保流程',
  },
  {
    riskName: '灾难恢复能力不足',
    controlMeasure: '信息技术部建立同城与异地双活数据中心',
    controlLevel: '总公司',
    headDeptHQ: '信息技术部',
    headDeptProvince: '无',
    headDeptCity: '无',
    headDeptCounty: '无',
    controlSystem: '系统自动控制',
    controlDesc: 'RPO≤1小时，RTO≤4小时，每年全链路演练一次',
  },
]
